FROM caddy:2-builder AS builder

RUN xcaddy build \
    --with github.com/caddy-dns/duckdns

FROM caddy:2-alpine

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
COPY deployment/caddy-entrypoint.sh /usr/local/bin/caddy-entrypoint.sh

RUN chmod +x /usr/local/bin/caddy-entrypoint.sh
